# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 80, host: 8456

  config.vm.synced_folder "../", "/app"

  config.vm.provider "virtualbox" do |vb|
  #  vb.gui = true
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo ln -fs /usr/share/zoneinfo/GMT /etc/localtime
    sudo bash -c 'cd /app; source /app/make-env.sh'
  SHELL
end
